export interface Mood {
  slug: string;
  label: string;
  emoji: string;
  description: string;
  withGenres: string;
  sortBy?: string;
  voteCountGte?: number;
}

// Genre IDs are TMDB's standard movie genre IDs. "|" = match ANY, "," = match ALL.
export const MOODS: Mood[] = [
  {
    slug: "cozy-sunday",
    label: "Cozy Sunday",
    emoji: "🛋️",
    description: "Warm, easy comfort watches — family and comedy.",
    withGenres: "10751|35",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "edge-of-your-seat",
    label: "Edge of Your Seat",
    emoji: "😬",
    description: "Tense thrillers and mysteries that keep you guessing.",
    withGenres: "53,9648",
    sortBy: "vote_average.desc",
    voteCountGte: 200,
  },
  {
    slug: "feel-good",
    label: "Feel-Good",
    emoji: "🌤️",
    description: "Comedy and romance to lift your mood.",
    withGenres: "35,10749",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "mind-bending",
    label: "Mind-Bending",
    emoji: "🧠",
    description: "Sci-fi and mystery that mess with reality.",
    withGenres: "878,9648",
    sortBy: "vote_average.desc",
    voteCountGte: 200,
  },
  {
    slug: "popcorn-action",
    label: "Popcorn Action",
    emoji: "💥",
    description: "Big, loud action and adventure blockbusters.",
    withGenres: "28,12",
    sortBy: "popularity.desc",
    voteCountGte: 200,
  },
  {
    slug: "spooky-night",
    label: "Spooky Night",
    emoji: "🎃",
    description: "Horror and thrillers for a scary movie night.",
    withGenres: "27|53",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "true-crime",
    label: "True Crime",
    emoji: "🔍",
    description: "Crime dramas and documentaries based on real events.",
    withGenres: "80|99",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "epic-adventure",
    label: "Epic Adventure",
    emoji: "🗺️",
    description: "Fantasy and adventure worlds to get lost in.",
    withGenres: "14,12",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "ugly-cry",
    label: "Ugly Cry",
    emoji: "😭",
    description: "Emotional dramas that will absolutely wreck you.",
    withGenres: "18",
    sortBy: "vote_average.desc",
    voteCountGte: 300,
  },
  {
    slug: "belly-laughs",
    label: "Belly Laughs",
    emoji: "🤣",
    description: "Pure, unfiltered comedy — nothing serious allowed.",
    withGenres: "35",
    sortBy: "popularity.desc",
    voteCountGte: 200,
  },
  {
    slug: "date-night",
    label: "Date Night",
    emoji: "💑",
    description: "Romance with just enough drama to spark conversation.",
    withGenres: "10749,18",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "family-movie-night",
    label: "Family Movie Night",
    emoji: "👨‍👩‍👧‍👦",
    description: "Animated and family-friendly picks for all ages.",
    withGenres: "16,10751",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "outer-space",
    label: "Outer Space",
    emoji: "🚀",
    description: "Sci-fi voyages beyond the stars.",
    withGenres: "878",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "war-stories",
    label: "War Stories",
    emoji: "🎖️",
    description: "Gripping war dramas and history in the trenches.",
    withGenres: "10752,36",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "musical-mood",
    label: "Musical Mood",
    emoji: "🎵",
    description: "Music-driven films and toe-tapping musicals.",
    withGenres: "10402",
    sortBy: "popularity.desc",
    voteCountGte: 80,
  },
  {
    slug: "western-frontier",
    label: "Western Frontier",
    emoji: "🤠",
    description: "Gunslingers, outlaws, and the wild frontier.",
    withGenres: "37",
    sortBy: "popularity.desc",
    voteCountGte: 50,
  },
  {
    slug: "animated-worlds",
    label: "Animated Worlds",
    emoji: "🎨",
    description: "Animation for every age, from studios worldwide.",
    withGenres: "16",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "war-of-nerves",
    label: "War of Nerves",
    emoji: "🕵️",
    description: "Espionage, spies, and political intrigue.",
    withGenres: "53,10752",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "high-fantasy",
    label: "High Fantasy",
    emoji: "🐉",
    description: "Sword-and-sorcery epics and magical realms.",
    withGenres: "14",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "gritty-crime",
    label: "Gritty Crime",
    emoji: "🔫",
    description: "Hard-boiled crime and gangster sagas.",
    withGenres: "80",
    sortBy: "vote_average.desc",
    voteCountGte: 200,
  },
  {
    slug: "documentary-deep-dive",
    label: "Documentary Deep Dive",
    emoji: "🎥",
    description: "Real stories, real people, real events.",
    withGenres: "99",
    sortBy: "vote_average.desc",
    voteCountGte: 50,
  },
  {
    slug: "supernatural-thrills",
    label: "Supernatural Thrills",
    emoji: "👻",
    description: "Ghosts, curses, and things that go bump in the night.",
    withGenres: "27,14",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "coming-of-age",
    label: "Coming of Age",
    emoji: "🌱",
    description: "Growing up, first loves, and finding yourself.",
    withGenres: "18,10751",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "heist-and-hustle",
    label: "Heist & Hustle",
    emoji: "💰",
    description: "Clever cons, big scores, and slick criminals.",
    withGenres: "80,28",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "courtroom-drama",
    label: "Courtroom Drama",
    emoji: "⚖️",
    description: "Legal battles, twists, and justice on trial.",
    withGenres: "18,9648",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "disaster-and-survival",
    label: "Disaster & Survival",
    emoji: "🌋",
    description: "Nature, catastrophe, and the fight to survive.",
    withGenres: "28,12",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "underdog-sports",
    label: "Underdog Sports Stories",
    emoji: "🏆",
    description: "Against-the-odds athletes and true grit.",
    withGenres: "18,99",
    sortBy: "vote_average.desc",
    voteCountGte: 80,
  },
  {
    slug: "buddy-comedy",
    label: "Buddy Comedy",
    emoji: "🤝",
    description: "Mismatched duos and hilarious chemistry.",
    withGenres: "35,12",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "psychological-thriller",
    label: "Psychological Thriller",
    emoji: "🌀",
    description: "Unreliable narrators and twisted minds.",
    withGenres: "53,18",
    sortBy: "vote_average.desc",
    voteCountGte: 200,
  },
  {
    slug: "found-footage-horror",
    label: "Found Footage Horror",
    emoji: "📹",
    description: "Raw, unsettling horror shot like it's real.",
    withGenres: "27,9648",
    sortBy: "popularity.desc",
    voteCountGte: 60,
  },
  {
    slug: "slow-burn-mystery",
    label: "Slow-Burn Mystery",
    emoji: "🕵️‍♀️",
    description: "Whodunits that reward patience.",
    withGenres: "9648",
    sortBy: "vote_average.desc",
    voteCountGte: 150,
  },
  {
    slug: "swashbuckling-adventure",
    label: "Swashbuckling Adventure",
    emoji: "⚔️",
    description: "Pirates, treasure, and daring escapes.",
    withGenres: "12,14",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "workplace-comedy",
    label: "Workplace Comedy",
    emoji: "💼",
    description: "Office chaos and career catastrophes played for laughs.",
    withGenres: "35,18",
    sortBy: "popularity.desc",
    voteCountGte: 80,
  },
  {
    slug: "monster-mayhem",
    label: "Monster Mayhem",
    emoji: "👹",
    description: "Giant creatures and things that shouldn't exist.",
    withGenres: "27,878",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "road-trip",
    label: "Road Trip",
    emoji: "🚗",
    description: "Journeys, detours, and life-changing miles.",
    withGenres: "12,35",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "political-intrigue",
    label: "Political Intrigue",
    emoji: "🏛️",
    description: "Power plays, conspiracies, and the corridors of government.",
    withGenres: "18,53",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "revenge-tales",
    label: "Revenge Tales",
    emoji: "🗡️",
    description: "Cold, calculated paybacks and justice served hard.",
    withGenres: "28,53",
    sortBy: "popularity.desc",
    voteCountGte: 150,
  },
  {
    slug: "small-town-secrets",
    label: "Small Town Secrets",
    emoji: "🏘️",
    description: "Quiet towns hiding dark truths.",
    withGenres: "9648,18",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "kaiju-and-monsters",
    label: "Kaiju & Giant Monsters",
    emoji: "🦖",
    description: "City-stomping creatures and the humans who fight them.",
    withGenres: "878,28",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "biopic-legends",
    label: "Biopic Legends",
    emoji: "🎤",
    description: "Real lives, larger than life, on screen.",
    withGenres: "18,36",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "cult-classics",
    label: "Cult Classics",
    emoji: "🌀",
    description: "Weird, wonderful films with devoted followings.",
    withGenres: "35,878",
    sortBy: "vote_average.desc",
    voteCountGte: 250,
  },
  {
    slug: "post-apocalyptic",
    label: "Post-Apocalyptic",
    emoji: "☢️",
    description: "The world's ended — now what?",
    withGenres: "878,28",
    sortBy: "vote_average.desc",
    voteCountGte: 150,
  },
  {
    slug: "holiday-classics",
    label: "Holiday Classics",
    emoji: "🎄",
    description: "Feel-good films for the festive season.",
    withGenres: "10751,10749",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "true-love-epics",
    label: "True Love Epics",
    emoji: "💞",
    description: "Sweeping romances across time and distance.",
    withGenres: "10749,18",
    sortBy: "vote_average.desc",
    voteCountGte: 200,
  },
  {
    slug: "one-night-adventures",
    label: "One Wild Night",
    emoji: "🌃",
    description: "Everything goes wrong in the best possible way.",
    withGenres: "35,80",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "prestige-drama",
    label: "Prestige Drama",
    emoji: "🏅",
    description: "Award-caliber storytelling and performances.",
    withGenres: "18",
    sortBy: "vote_average.desc",
    voteCountGte: 500,
  },
  {
    slug: "guilty-pleasure",
    label: "Guilty Pleasure",
    emoji: "🍿",
    description: "So bad it's good, or just plain fun.",
    withGenres: "35,10749,27",
    sortBy: "popularity.desc",
    voteCountGte: 50,
  },
  {
    slug: "corporate-thriller",
    label: "Corporate Thriller",
    emoji: "🏢",
    description: "Boardrooms, betrayal, and billion-dollar stakes.",
    withGenres: "53,18",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "time-travel-tales",
    label: "Time Travel Tales",
    emoji: "⏳",
    description: "Loops, paradoxes, and altered timelines.",
    withGenres: "878,12",
    sortBy: "vote_average.desc",
    voteCountGte: 150,
  },
  {
    slug: "underwater-adventure",
    label: "Underwater Adventure",
    emoji: "🌊",
    description: "The deep sea and everything lurking in it.",
    withGenres: "12,27",
    sortBy: "popularity.desc",
    voteCountGte: 60,
  },
  {
    slug: "chosen-one-sagas",
    label: "Chosen One Sagas",
    emoji: "⚡",
    description: "Prophecies, destinies, and unlikely heroes.",
    withGenres: "14,12",
    sortBy: "popularity.desc",
    voteCountGte: 200,
  },
  {
    slug: "slasher-marathon",
    label: "Slasher Marathon",
    emoji: "🔪",
    description: "Classic and modern slasher horror.",
    withGenres: "27",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "art-house-cinema",
    label: "Art House Cinema",
    emoji: "🎞️",
    description: "Bold, unconventional filmmaking.",
    withGenres: "18,9648",
    sortBy: "vote_average.desc",
    voteCountGte: 300,
  },
  {
    slug: "military-ops",
    label: "Military Ops",
    emoji: "🪖",
    description: "Special forces, missions, and modern warfare.",
    withGenres: "28,10752",
    sortBy: "popularity.desc",
    voteCountGte: 100,
  },
  {
    slug: "haunted-houses",
    label: "Haunted Houses",
    emoji: "🏚️",
    description: "Creaky floors, cold spots, and things in the walls.",
    withGenres: "27",
    sortBy: "vote_average.desc",
    voteCountGte: 100,
  },
  {
    slug: "quirky-indie",
    label: "Quirky Indie",
    emoji: "🎈",
    description: "Offbeat characters and small-scale charm.",
    withGenres: "35,18,10749",
    sortBy: "vote_average.desc",
    voteCountGte: 150,
  },
  {
    slug: "animal-companions",
    label: "Animal Companions",
    emoji: "🐾",
    description: "Films where the animal steals the show.",
    withGenres: "10751,12",
    sortBy: "popularity.desc",
    voteCountGte: 80,
  },
];

export function getMood(slug: string) {
  return MOODS.find((m) => m.slug === slug) ?? null;
}
